apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: java-props
   labels:
     name: dummy-service-selector #configured
spec:
   replicas: 1
   selector:
     matchLabels:
       name: dummy-service-selector
   template:
     metadata:
       labels:
         name: dummy-service-selector
     spec:
       containers:
       - image: pregistry.dnsk.io:5000/agt/dummy-service:latest #configured
         name: dummy-service-selector
         imagePullPolicy: Always
         volumeMounts:
         - mountPath: /opt/config
           name: config-volume
#         env:
#         - name: APP_HOME
#           value: /opt/app
         ports:
         - containerPort: 8080 #configured
       volumes:
       # consume the file-like keys of the configmap via volume plugin
       - name: config-volume
         configMap:
          name: my-config
          items:
          - key: application.properties
            path: application.properties