apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: java-props
   labels:
       name: hello-world-java
spec:
   replicas: 1
   selector:
     matchLabels:
       name: hello-world-java
   template:
     metadata:
       labels:
         name: hello-world-java
     spec:
       containers:
       - image: 911479539546.dkr.ecr.us-east-1.amazonaws.com/hello-world-java:0.1.0
         name: hello-world-java
         imagePullPolicy: Always
         volumeMounts:
         - mountPath: /opt/config
           name: config-volume
         ports:
         - containerPort: 8080
       volumes:
       - name: config-volume