pipeline:
  test:
    image: docker.heed-dev.io/aws-k8s-docker
    pull: true
    commands:
      - pip install -r requirements.txt
      - /opt/login.sh
      - kubectl-conf int --kops
      - python -m nose
      - behave -D mode=aws features
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  publish:
    image: plugins/ecr
    repo: 911479539546.dkr.ecr.us-east-1.amazonaws.com/k8s-deployer
    secrets: [ecr_secret_key,ecr_access_key]
    tags: latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: develop
