pipeline:
  test:
    image: docker.heed-dev.io/aws-k8s-docker
    environment:
      - MONGO_HOST=mongo
    pull: true
    commands:
      - sh /opt/login.sh
      - pip install -r requirements.txt
      - kubectl-conf int --kops
      - python -m nose
      - behave -D mode=aws features
    secrets:
      - source: aws_dev_access_key_id
        target: aws_access_key_id
      - source: aws_dev_secret_key
        target: aws_secret_access_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  publish:
    image: plugins/ecr
    repo: 911479539546.dkr.ecr.us-east-1.amazonaws.com/k8s-deployer
    secrets: [ecr_secret_key,ecr_access_key]
    tags: 1.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: develop

services:
  mongo:
    image: mongo