pipeline:
  test:
    image: registry.dnsk.io:5000/agt/aws-k8s-docker
    pull: true
    commands:
      - pip install -r requirements.txt
      - python -m nose test
      - behave -D mode=aws features
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  publish:
    image: plugins/docker
    repo: registry.dnsk.io:5000/agt/k8s-deployer
    tags: 1.2.0
    when:
      branch: develop
