pipeline:
  test:
    image: registry.dnsk.io:5000/agt/aws-k8s-docker
    pull: true
    commands:
      - pip install -r requirements.txt
      - python -m nose test
      - kubectl-conf int --kops
      - python -m nose test_it
      - behave -D mode=aws features

  publish:
    image: plugins/docker
    repo: registry.dnsk.io:5000/agt/k8s-deployer
    tags: latest
    when:
      branch: develop
