apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: java-props
   labels:
     name: {serviceSelector} #configured
spec:
   replicas: 1
   selector:
     matchLabels:
       name: {serviceSelector}
   template:
     metadata:
       labels:
         name: {serviceSelector}
     spec:
       containers:
#       - image: pregistry.dnsk.io:5000/agt/{serviceName}:latest #configured
       - image: {image}
         name: {serviceSelector}
         imagePullPolicy: Always
         volumeMounts:
         - mountPath: /opt/config
           name: config-volume
#         env:
#         - name: APP_HOME
#           value: /opt/app
         ports:
         - containerPort: {containerPort} #configured
       volumes:
       # consume the file-like keys of the configmap via volume plugin
       - name: config-volume