apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: {name}-{podColor}
   labels:
       name: {name}-{podColor}
spec:
   replicas: 1
   selector:
     matchLabels:
       name: {name}-{podColor}
   template:
     metadata:
       labels:
         name: {name}-{podColor}
         type: {name}-{podColor}
         color: {podColor}
     spec:
       containers:
       - image: {image}
         name: {name}-{podColor}
         imagePullPolicy: Always
         volumeMounts:
         # the config folder should be inside the folder where we run java
         # (equals to APP_HOME in the Dockerfile of dockerize)
         - mountPath: /opt/service/config
           name: config-volume
         ports:
         - name: liveness-port
           containerPort: 8080
         livenessProbe:
           httpGet:
             path: /health
             port: liveness-port
           initialDelaySeconds: 30
           timeoutSeconds: 1
       volumes:
         - name: config-volume
           configMap:
             name: global-config
             items:
             - key: global.yml
               path: application.yml