apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: {name}
   myenv: {env}
   labels:
       name: {name}
spec:
   replicas: 1
   selector:
     matchLabels:
       name: {name}
   template:
     metadata:
       labels:
         name: {name}
         type: {name}
         color: {podColor}
     spec:
       containers:
       - image: {image}
         name: {name}
         imagePullPolicy: Always
         volumeMounts:
         # the config folder should be inside the folder where we run java
         # (equals to APP_HOME in the Dockerfile of dockerize)
         - mountPath: /opt/service/config
           name: config-volume
         ports:
         - name: liveness-port
           containerPort: 8080
         livenessProbe:
           httpGet:
             path: /health
             port: liveness-port
           initialDelaySeconds: 30
           timeoutSeconds: 1
         env:
           - name: MY_POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: MY_POD_NAMESPACE
             valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
            - name: MY_ENV
                valueFrom:
                 fieldRef:
                   fieldPath: metadata.myenv
       volumes:
         - name: config-volume
           configMap:
             name: global-config
             items:
             - key: global.yml
               path: application.yml