apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: {name}
   labels:
       name: {name}
spec:
   replicas: 1
   selector:
     matchLabels:
       name: {name}
   template:
     metadata:
       labels:
         name: {name}
         type: {name}
         color: {podColor}
     spec:
       containers:
       - image: {image}
         name: {name}
         volumeMounts:
         - name: shared-logs
           mountPath: /opt/log/
         - name: config-volume
           mountPath: /opt/service/config

         ports:
         - name: liveness-port
           containerPort: 8080
         livenessProbe:
           httpGet:
             path: /health
             port: liveness-port
           initialDelaySeconds: 30
           timeoutSeconds: 1
         env:
           - name: MY_POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: MY_POD_NAMESPACE
             valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
           - name: MY_ENV
             value: {myEnv}
       - name: fluentd-kubernetes
         image: 911479539546.dkr.ecr.us-east-1.amazonaws.com/fluentd:latest
         env:
           - name: ELASTICSEARCH_HOST
             value: "elkdev.heedapps.io"
           - name: ELASTICSEARCH_USER
             valueFrom:
               secretKeyRef:
                 name: es-secrets
                 key: user
           - name: ELASTICSEARCH_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: es-secrets
                 key: password
           - name: FLUENTD_LOGSTASH_PREFIX
             value: "log4j"
           - name: SERVICE_NAME
             valueFrom:
               fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.name
           - name: ENVIRONMENT
             value: int
         imagePullPolicy: Always
         volumeMounts:
         - name: shared-logs
           mountPath: /opt/log/
       volumes:
         - name: shared-logs
           emptyDir: {}
         - name: config-volume
           configMap:
             name: global-config
             items:
             - key: global.yml
               path: application.yml
