apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: {name}
   labels:
       name: {name}
spec:
   replicas: 1
   selector:
     matchLabels:
       name: {name}
   template:
     metadata:
       labels:
         name: {name}
     spec:
       containers:
       - image: {image}
         name: {name}
         imagePullPolicy: Always
         volumeMounts:
         - mountPath: /opt/config
           name: config-volume
         ports:
         - name: liveness-port
           containerPort: 8080
         livenessProbe:
           httpGet:
             path: /health
             port: liveness-port
           initialDelaySeconds: 30
           timeoutSeconds: 1
       volumes:
       - name: config-volume