apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: java-props
   labels:
       name: {name}
spec:
   replicas: 1
   selector:
     matchLabels:
       name: {name}
   template:
     metadata:
       labels:
         name: {name}
     spec:
       containers:
       - image: 911479539546.dkr.ecr.us-east-1.amazonaws.com/{name}:0.1.0
         name: {name}
         imagePullPolicy: Always
         volumeMounts:
         - mountPath: /opt/config
           name: config-volume
         ports:
         - containerPort: 8080
       volumes:
       - name: config-volume