kind: Service
apiVersion: v1
metadata:
  name: {serviceName} #configured
  labels:
    name: {serviceName}
    dns: route53
    auto-ingress: yes
  annotations:
      domainName: {env}-k8s-{serviceName}.heedapps.io
spec:
  selector:
    name: {serviceName}-{serviceColor}
    color: {serviceColor}
    type : {serviceName}-{serviceColor}
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 80
  type: LoadBalancer
