kind: Service
apiVersion: v1
metadata:
  name: {name}-service #configured
  labels:
    name: {name}
spec:
  selector:
    name: {name} #configured
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 80
  type: LoadBalancer
