apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: {name}
   labels:
       name: {name}
spec:
   replicas: 1
   revisionHistoryLimit: 10
   selector:
     matchLabels:
       name: {name}
   template:
     metadata:
       labels:
         name: {name}
         type: {name}
         color: {podColor}
     spec:
       containers:
       - image: {image}
         name: {name}
         volumeMounts:
         - name: shared-logs
           mountPath: /opt/log/
         - name: config-volume
           mountPath: /opt/service/config

         ports:
         - name: liveness-port
           containerPort: 8080
         livenessProbe:
           httpGet:
             path: /health
             port: liveness-port
           initialDelaySeconds: 30
           timeoutSeconds: 1
         env:
           - name: MY_POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: MY_POD_NAMESPACE
             valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
           - name: MY_ENV
             value: {myEnv}
       volumes:
         - name: shared-logs
           emptyDir: {{}}
         - name: config-volume
           configMap:
             name: global-config
             items:
             - key: global.yml
               path: application.yml
